Repository reactjs/nl.reactjs.org, pull requests merged in 2019-02, with the labels that each got.

#11 Translate docs/introducing-jsx.md
  content/docs/introducing-jsx.md
  content/docs/nav.yml
Labels: ⏳Waiting For Author

#14 Fix mixed content build error
  content/blog/2015-03-30-community-roundup-26.md
Labels: 🔍Looking For Reviews

#19 Translate docs/event-handling.md
  content/docs/handling-events.md
Labels: :+1:Need +1

#13 Translate docs/rendering-elements.md
  content/docs/nav.yml
  content/docs/rendering-elements.md
Labels: 🔍Looking For Reviews

#17 Translate homepage
  content/home/examples/a-component-using-external-plugins.md
  content/home/examples/a-simple-component.md
  content/home/examples/a-stateful-component.md
  content/home/examples/an-application.md
  content/home/marketing/component-based.md
  content/home/marketing/declarative.md
  content/home/marketing/learn-once-write-anywhere.md
Labels: :+1:Need +1

#25 Capitalize all words in section titles (cfr. style guidelines)
  content/docs/handling-events.md
  content/docs/introducing-jsx.md
  content/docs/nav.yml
  content/docs/rendering-elements.md
Labels: :+1:Need +1
